version: '3'
services:
  module1:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    links:
      - module2
    # ...

  module2:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    # ...

  # module2:
  #   image: mageai/mageai:latest
  #   command: mage start ${PROJECT_NAME}
  #   env_file:
  #     - .env
  #   build:
  #     context: ./module2
  #     dockerfile: Dockerfile
  #   environment:
  #     USER_CODE_PATH: /home/src/${PROJECT_NAME}
  #     POSTGRES_DBNAME: ${POSTGRES_DBNAME}
  #     POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #   ports:
  #     - 6789:6789
  #   volumes:
  #     - .:/workspace:cached
  #     # - ~/Documents/secrets/personal-gcp.json:/home/src/personal-gcp.json
  #   restart: on-failure:5
  
  # postgres:
  #   image: postgres:13
  #   restart: on-failure
  #   container_name: ${PROJECT_NAME}-postgres
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DBNAME}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
